server:
  port: 3333
  
management:
  server:
   port: 9001
    
  endpoints:
    web:
      exposure:
        include: "*"
springdoc:
  swagger-ui:
    path: /swagger-ui.html


eureka:
  client:
    register-with-eureka: false
    fetch-registry: true

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/javabatch
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
       format_sql: true
  application:
    name: product
